[profile.default]
out = 'foundry-out'
solc_version = '0.8.26'
optimizer_runs = 200000
via_ir = true 
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
evm_version = "cancun"
gas_limit = "3000000000"
fuzz_runs = 10_000
bytecode_hash = "none"

[profile.debug]

optimizer_runs = 44444444
fuzz.runs = 100

[profile.ci]
fuzz_runs = 100_000

[profile.gas]
gas_limit=30_000_000


remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "forge-gas-snapshot/=lib/forge-gas-snapshot/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "solmate/=lib/solmate/src/"
]

# Optional: Include only contracts directory
include = ['src']
exclude = [
    'test',                             # Exclude test contracts
    'lib/forge-gas-snapshot/src',       # Unused snapshot utility
    'lib/forge-std/src',                # Standard foundry tools
    'lib/ds-test/src',                  # DS-Test library
    'lib/openzeppelin-contracts/contracts/mocks', # Mock contracts
    'lib/solmate/src/test',             # Solmate test utilities
    'lib/v4-core/test',                 # Uniswap Core tests
    'lib/v4-core/periphery',            # Periphery contracts if unused
    'lib/v4-core/examples',             # Example contracts if unused
    'lib/v4-core/interfaces/test',      # Test interfaces
    'lib/v4-core/hooks/test'            # Test hooks
]



# See more config options https://github.com/foundry-rs/foundry/tree/master/config